version: '1.0.{build}'

#platform:
#  - x86
#  - x64

environment:
  matrix:
    - ruby_version: "193"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23-x64"
      CHILDPROCESS_POSIX_SPAWN: true
      CHILDPROCESS_UNSET: should-be-unset

    - ruby_version: "193"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "193-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "200-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "21-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "22-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset
    - ruby_version: "23-x64"
      CHILDPROCESS_POSIX_SPAWN: false
      CHILDPROCESS_UNSET: should-be-unset

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
